version: '3.3'

services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app
      - ../media:/app/media
      - ../backend/data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
    command: >
      sh -c "python3 manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 foodgram_backend.wsgi:application"


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - backend
    command: >
      npm start

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../backend/media:/app/media
      - ../backend/static:/app/static
      - ../docs/:/usr/share/nginx/html/docs/
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
